### ISSUE TITLE
 Cannot read property 'keycloak-token' of undefined

### ISSUE THREAD

**Issue by divukman** [ddezoysa/keycloak-nodejs-microservice#1]
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
Initializing Keycloak...
TypeError: Cannot read property 'keycloak-token' of undefined

Might be related to: https://stackoverflow.com/questions/56286958/how-to-fix-typeerror-cannot-read-property-keycloak-token-of-undefined-error

**Comment by divukman** [comment]
Im not sure why the code does not work, following example from https://github.com/keycloak/keycloak-quickstarts/blob/latest/service-nodejs/app.js has fixed the issue for me.

**Comment by titobundy** [comment]
> [nodemon] 2.0.4
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): _._
> [nodemon] watching extensions: js,mjs,json
> [nodemon] starting `node index.js`
> Initializing Keycloak...
> TypeError: Cannot read property 'keycloak-token' of undefined
> 
> Might be related to: https://stackoverflow.com/questions/56286958/how-to-fix-typeerror-cannot-read-property-keycloak-token-of-undefined-error

I have the same error, but only with public endpoints, ie http://localhost:3000/test/anonymous, if I setup any value in Authorization Bearer Token like '123' its works again, but not works with 'No Auth'.

**Comment by pipe27febrero** [comment]
to fix this issue do the following :
add memoryStore in **index.js a**nd pass as variable in initKeycloak method as follows
`const session = require('express-session')`
`var memoryStore = new session.MemoryStore(); `
`app.use(session({
   secret: 'some secret',
   resave: false,
   saveUninitialized: true,
   store: memoryStore
 })); `
`const keycloak = require('./config/keycloak-config.js').initKeycloak(memoryStore);`

in **keycloak-config.js** file we'll make some changes in initKeycloak() method now passing memoryStore as argument
`function initKeycloak(memoryStore) {
    if (_keycloak) {
        console.warn("Trying to init Keycloak again!");
        return _keycloak;
    } 
    else {
        console.log("Initializing Keycloak...");
        _keycloak = new Keycloak({ store: memoryStore }, keycloakConfig);
        return _keycloak;
    }
}`

**Comment by suiciniv87** [comment]
> to fix this issue do the following :
> add memoryStore in **index.js a**nd pass as variable in initKeycloak method as follows
> `const session = require('express-session')`
> `var memoryStore = new session.MemoryStore(); `
> `app.use(session({ secret: 'some secret', resave: false, saveUninitialized: true, store: memoryStore })); `
> `const keycloak = require('./config/keycloak-config.js').initKeycloak(memoryStore);`
> 
> in **keycloak-config.js** file we'll make some changes in initKeycloak() method now passing memoryStore as argument
> `function initKeycloak(memoryStore) { if (_keycloak) { console.warn("Trying to init Keycloak again!"); return _keycloak; } else { console.log("Initializing Keycloak..."); _keycloak = new Keycloak({ store: memoryStore }, keycloakConfig); return _keycloak; } }`

it worked for me! The 'some secret' is the same of credentials in keycloakConfig, correct?

**Comment by MinuraKariyawasam** [comment]
> to fix this issue do the following :
> add memoryStore in **index.js a**nd pass as variable in initKeycloak method as follows
> `const session = require('express-session')`
> `var memoryStore = new session.MemoryStore(); `
> `app.use(session({ secret: 'some secret', resave: false, saveUninitialized: true, store: memoryStore })); `
> `const keycloak = require('./config/keycloak-config.js').initKeycloak(memoryStore);`
> 
> in **keycloak-config.js** file we'll make some changes in initKeycloak() method now passing memoryStore as argument
> `function initKeycloak(memoryStore) { if (_keycloak) { console.warn("Trying to init Keycloak again!"); return _keycloak; } else { console.log("Initializing Keycloak..."); _keycloak = new Keycloak({ store: memoryStore }, keycloakConfig); return _keycloak; } }`

it worked, thank for the feedback.

**Comment by yolepro** [comment]
> 

It worked for me too, but the 'some secret' can be kept as is and it's working.

**Comment by ddezoysa** [comment]
Closing the issue as the answer is already provided in the comments.
